# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasicConfigWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InitialSettingsWindow(object):
    def __init__(self, MainWindow):
        super(Ui_InitialSettingsWindow, self).__init__()
        self.setupUi(MainWindow)

    def setupUi(self, InitialSettingsWindow):
        InitialSettingsWindow.setObjectName("InitialSettingsWindow")
        InitialSettingsWindow.resize(437, 382)
        self.centralwidget = QtWidgets.QWidget(InitialSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serverIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverIPLabel.setObjectName("serverIPLabel")
        self.verticalLayout.addWidget(self.serverIPLabel)
        self.serverLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serverLineEdit.setObjectName("serverLineEdit")
        self.verticalLayout.addWidget(self.serverLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderPathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.folderPathLineEdit.setObjectName("folderPathLineEdit")
        self.horizontalLayout.addWidget(self.folderPathLineEdit)
        self.discoverFilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.discoverFilesButton.setObjectName("discoverFilesButton")
        self.horizontalLayout.addWidget(self.discoverFilesButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setObjectName("continueButton")
        self.verticalLayout.addWidget(self.continueButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        InitialSettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InitialSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(InitialSettingsWindow)

    def retranslateUi(self, InitialSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        InitialSettingsWindow.setWindowTitle(_translate("InitialSettingsWindow", "Basic Details"))
        self.serverIPLabel.setText(_translate("InitialSettingsWindow", "Server IP"))
        self.serverLineEdit.setPlaceholderText(_translate("InitialSettingsWindow", "Enter Server IP"))
        self.pathLabel.setText(_translate("InitialSettingsWindow", "Public Folder Path"))
        self.folderPathLineEdit.setPlaceholderText(_translate("InitialSettingsWindow", "Enter Public Folder Path"))
        self.discoverFilesButton.setText(_translate("InitialSettingsWindow", "Open"))
        self.continueButton.setText(_translate("InitialSettingsWindow", "Continue"))
