# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import logging
import socket
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

sys.path.append("client")
from ui.BasicConfigWindow import Ui_InitialSettingsWindow

CLIENT_IP = socket.gethostbyname(socket.gethostname())
# Logging configuration
logging.basicConfig(level=logging.DEBUG)

class Ui_StartWindow(object):
    def __init__(self, MainWindow):
        super(Ui_StartWindow, self).__init__()
        self.setupUi(MainWindow)

    def setupUi(self, StartWindow) -> None:
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(375, 340)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.echoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.echoLabel.setFont(font)
        self.echoLabel.setObjectName("echoLabel")
        self.verticalLayout.addWidget(self.echoLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout.addWidget(self.usernameEdit)
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setObjectName("continueButton")
        self.horizontalLayout.addWidget(self.continueButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        StartWindow.setCentralWidget(self.centralwidget)

        self.continueButton.clicked.connect(
            lambda: self.on_continueButton_clicked(StartWindow))

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Welcome To Echo"))
        self.echoLabel.setText(_translate("StartWindow", "Echo"))
        self.usernameEdit.setPlaceholderText(_translate("StartWindow", "Enter Your Username"))
        self.continueButton.setText(_translate("StartWindow", "Continue"))

    def on_continueButton_clicked(self, MainWindow) -> None:
        #open BasicConfigWindow.py and close the current window
        MainWindow.user_settings["uname"] = self.usernameEdit.text()
        logging.debug(f"Username updated, new settings: {MainWindow.user_settings}")
        MainWindow.ui = Ui_InitialSettingsWindow(MainWindow)
        # self.closewin()
    
    def closewin(self) -> None:
        self.close()
